### PR TITLE
Support for node_modules in graphql imports

### PR DESCRIPTION
**Pull request by lfades**
Before (manual search for `node_modules` folder):
```gql
# import Auth from '../../node_modules/module-name/auth.graphql'
```
Now:
```gql
# import Auth from 'module-name/auth.graphql'
```

### CODE REVIEW

**Comment by schickling** [comment]
Can you please rebase so I can merge?

Also, can you please add a test case for this? You might need to add another `.gitignore` file.

**Comment by lfades** [comment]
@schickling Sure, I'm working on it

**Comment by lfades** [comment]
@schickling How should be done the test case ? I can probably install a package as a dev dependency that has graphql files and import one of those, or can you see a better way ?

**Comment by schickling** [comment]
You can also "manually create" a `node_modules` folder + an example package in the corresponding test folder and explicitly allow it in the `.gitignore`. This way you don't need to install it as a dependency.

**Comment by lfades** [comment]
Tests added, please keep in mind that the following code will still not work:

```js
importSchema('module-name/a.graphql')
```

It would introduce a breaking chance

**Comment by schickling** [comment]
The tests still seem to fail. Can you look into it and fix it?

**Comment by lfades** [comment]
yep, checks for node are failing here

image

I already pushed that [folder](https://github.com/lfades/graphql-import/tree/import-modules/node_modules/graphql-import-test) and tests are passing, do you have any idea of how can I replicate that behaviour ?

**Comment by lfades** [comment]
@SpaceK33z that makes a lot of sense, I'll add some `fs` code to the test 💃

**Comment by lfades** [comment]
One issue fixed, there's still one import that's not working in the CI but locally it does:

```gql
# import X from "a.graphql"
```

`"a.graphql"` is not found, I'll try to see what's happening

**Comment by lfades** [comment]
@schickling I found some bad news about this PR, it only works in Node < 8, I already know the solution but I don't like it, so I want to share my thoughts with you first:

[require.resolve](https://nodejs.org/api/modules.html#modules_require_resolve_request_options) is the main change done by this PR, the second param that it receives it's an object that has a `paths` option, which I use to make the import relative to the graphql file. The reason why it doesn't works in previous versions of node is because such option doesn't exists.

Possible solutions:

- By using internal code like the way eslint is doing it [here](https://github.com/eslint/eslint/blob/master/lib/util/module-resolver.js), related to this [issue](https://github.com/nodejs/node/issues/5963). I don't personally like this solution because we'll lose types and we'll need to use internal methods e.g `_.something`, but is an option
- Only allow module imports in newest versions of node

**Comment by tamlyn** [comment]
The [issue that lead to that feature](https://github.com/nodejs/node/issues/5963) being added to Node 8 lists a bunch of packages in the *Prior Art* section. [`resolve-from`](https://www.npmjs.com/package/resolve-from) gets >5m downloads a week and would probably be a good choice.

**Comment by kitten** [comment]
@tamlyn This seems to be the way to go.

@lfades It'd be awesome to see this in graphql-import and if you'd need help to bring this PR up to speed, I'm offering myself as a tribute

cc @schickling any objections to using `resolve-from` or this PR being picked up again? Btw #4 should probably reopened as this PR addresses it

**Comment by lfades** [comment]
If `resolve-from` is okay I can finish this PR with it

**Comment by SpaceK33z** [comment]
Still very much looking forward to this feature. Perhaps just finish the PR with the `resolve-from` as it seems to be the only way? I can help if you don't have the time.

**Comment by lfades** [comment]
Closed in favor of #216

**Pull request closed without merging**
